FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Copy the JAR file into the container
# COPY target/idgs09-0.0.1-SNAPSHOT.jar /app/mx-pe.jar
COPY target/idgs09_01-0.0.1-SNAPSHOT.jar /app/ms-pe.jar

# Expose the port the application will run on
EXPOSE 8080

#define la dentrada de la aplicacion
ENTRYPOINT ["java", "-jar", "ms-pe.jar"]